# Generated by Django 5.1.1 on 2025-03-24 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_alter_categoria_nombre_alter_usuario_contraseña_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
